//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftDevCase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class labo_salesEntities : DbContext
    {
        public labo_salesEntities()
            : base("name=labo_salesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ErrorCode> tbl_ErrorCode { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tbl_userType> tbl_userType { get; set; }
        public virtual DbSet<tbl_sales_detail> tbl_sales_detail { get; set; }
    
        public virtual ObjectResult<tbl_user> sp_GetUserDetails(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_user>("sp_GetUserDetails", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<tbl_user> sp_GetUserDetails(string username, string password, MergeOption mergeOption)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tbl_user>("sp_GetUserDetails", mergeOption, usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_GetErrorMessage_Result> sp_GetErrorMessage(string errorCode)
        {
            var errorCodeParameter = errorCode != null ?
                new ObjectParameter("errorCode", errorCode) :
                new ObjectParameter("errorCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetErrorMessage_Result>("sp_GetErrorMessage", errorCodeParameter);
        }
    
        public virtual int sp_InsertSalesDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertSalesDetails");
        }
    
        public virtual ObjectResult<sp_GetSalesReportDetails_Result> sp_GetSalesReportDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSalesReportDetails_Result>("sp_GetSalesReportDetails");
        }
    
        public virtual ObjectResult<sp_GetSalesReportDetailsByDate_Result> sp_GetSalesReportDetailsByDate(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> todate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSalesReportDetailsByDate_Result>("sp_GetSalesReportDetailsByDate", fromDateParameter, todateParameter);
        }
    
        public virtual ObjectResult<sp_getTopprofitableItemTypes_Result> sp_getTopprofitableItemTypes(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> todate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getTopprofitableItemTypes_Result>("sp_getTopprofitableItemTypes", fromDateParameter, todateParameter);
        }
    }
}
