//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftDevCase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_userType
    {
        public int userTypeId { get; set; }
        public string userTypeName { get; set; }
        public string userTypeDesc { get; set; }
    }
}
