//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftDevCase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sales_detail
    {
        public long id { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string Item_Type { get; set; }
        public string Sales_Channel { get; set; }
        public string Order_Priority { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public string Order_ID { get; set; }
        public Nullable<System.DateTime> Ship_Date { get; set; }
        public Nullable<int> Units_Sold { get; set; }
        public Nullable<double> Unit_Price { get; set; }
        public Nullable<double> Unit_Cost { get; set; }
        public Nullable<double> Total_Revenue { get; set; }
        public Nullable<double> Total_Cost { get; set; }
        public Nullable<double> Total_Profit { get; set; }
        public string uploaded_by { get; set; }
        public Nullable<System.DateTime> uploaded_date { get; set; }
    }
}
